// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"github.com/google/uuid"
)

type SwiftCode struct {
	ID             uuid.UUID
	Countrycode    string
	Swiftcode      string
	Codetype       string
	Name           string
	Address        string
	Townname       string
	Timezone       string
	Countryname    string
	Isheadquarter  bool
	Associatedwith int32
}
