services:
  db:
    image: postgres:15
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data3 # This is the volume that will be created, change /var/lib/postgresql/data to /var/lib/postgresql/<sthelse> if an error occurs
      - ./pg_hba.conf:/var/lib/postgresql/data3/pg_hba.conf # Then this to /var/lib/postgresql/<sthelse>
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  api:
    build: .
    depends_on:
      - db
    environment:
      DB_URL: postgres://postgres:password@db:5432/postgres?sslmode=disable
      PORT: 8080
    ports:
      - "8080:8080"


    volumes:
      - .:/usr/src


volumes:
  db_data:
    driver: local
