services:
  db:
    image: postgres:15
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  api:
    build: .
    depends_on:
      - db
    environment:
      DB_URL: postgres://postgres:password@db:5432/postgres?sslmode=disable
      PORT: 8080
    ports:
      - "8080:8080"
#    command: [ "go build", "./ApplicationRemitly" ]


    volumes:
      - .:/usr/src


#  goose:
#    build: .
#    depends_on:
#       - db
#    environment:
#        DB_DRIVER: postgres
#        DB_STRING: "user=postgres password=password dbname=postgres sslmode=disable host=db port=5432"
#    volumes:
#          - .:/usr/src
#    command: [ "up" ]

volumes:
  db_data:
